### ISSUE TITLE
Issue with k2_56v, value in ADC voltage ref + naming of ADC3_0 channel

### ISSUE THREAD

**Issue by Mariamahmed44** [abadr99/cpp_mcu_interface#41]
# Test Report
## Bugs found in test
- [x] **2.56v ref:** The value of bit 7 & 6 in register ADMUX should be 1 1 when its configured 2.56v as a ref voltage, instead its 0 1
- [x] **naming of ADC3_0 channel:** The naming of ADC3_0 should be ADC3_2 for 10x & for 200x
## Branch name
`refactor_ADC_tests`
## Pull request number
!42
## Notes
1) I think the for the first issue the value of 2.56v at the enum should be read as 3U instead of 17U

**Comment by abadr99** [comment]
Fixed by @Mariamahmed44
